version: "3.1"

services:
  db:
    container_name: prismaClient
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - prismaClient:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db:
